src/app/modules/card-cluster/card-cluster.component.css, src/app/modules/card-cluster/card-cluster.component.html, src/app/modules/card-cluster/card-cluster.component.ts
thicken the top border of active cards for clarity
=> update colors of card cluster for accessibility purposes

src/app/app.component.spec.ts, src/app/modules/calendar/calendar.component.spec.ts, src/app/modules/card-cluster/card-cluster.component.spec.ts, src/app/modules/popover/popover.component.html, src/app/modules/popover/popover.component.spec.ts, src/app/modules/toast/service/toast.service.spec.ts
Simple fixes to have successful runs of current happy path unit tests.
=> Unit test fixes

.prettierrc, package-lock.json, package.json, src/app/modules/text-field/text-field.component.html, src/app/modules/text-field/text-field.component.ts, src/app/modules/text-field/text-field.stories.ts, tslint.json
added linting and prettier enhancements
removed strange files
=> added option for multiline text field

src/app/modules/popover/popover.component.css, src/app/modules/popover/popover.component.html, src/app/modules/popover/popover.component.ts, src/app/modules/popover/popover.stories.ts, src/app/modules/spinner/spinner.component.html, src/app/modules/table2/table-cell/table-cell.component.html
Cleaning up focus classes on popover components
=> Styling a few components used in UM table

src/app/modules/table2/table-cell/table-cell.component.html, src/app/modules/table2/table-header/table-header.component.html
- fixing style issue with checkboxes and radios
=> Fixing header issue, and cut off choice

src/app/modules/choice/choice.component.html, src/app/modules/choice/choice.component.ts, src/app/modules/table2/table-cell/table-cell.component.html, src/app/modules/table2/table-header/table-header.component.html
- mostly formatting
- adding input for class on span containing label text in choice component
=> Hqrpp 25359/508 fixes

package.json, src/app/modules/chip-filter/chip-filter.component.html, src/app/modules/chip-filter/chip-filter.component.scss, src/app/modules/chip-filter/chip-filter.component.ts, src/app/modules/chip-filter/chip-filter.module.ts, src/app/modules/chip-filter/chip-filter.stories.ts, src/app/modules/chip-filter/story.const.ts, src/app/modules/table2/table.component.html, src/app/services/modal/modal.service.ts
1.) when chip filter is passed in the prop loader: true the loader should be displayed
2.) an event should emit when the chip filter results are scrolled to bottom so the host application can then set loader: true and make a request to server for more results
=> Hqrpp 26360 - adding loader to chip filter results

package.json, src/app/modules/chip-filter/chip-filter.component.ts, src/app/modules/chip-filter/chip-filter.stories.ts
Test the search field debounce in the with lazy loading spinner story
=> Adding debounce to search field change

package.json, src/app/modules/chip-filter/chip-filter.component.ts
HQRPP-26360 Stop overwriting filter search text when providers list is updated. Set filter onInit not onChange.
=> HQRPP-26360 Stop overwriting filter search text when providers list is updated

package-lock.json, package.json, src/app/modules/calendar/calendar.module.ts
Browser module imported twice (should just be common here)
=> Calendar Err

src/app/app.component.html, src/app/app.component.ts, src/app/modules/modal-shell/modal-generic/modal-generic.component.html, src/app/modules/modal-shell/modal-generic/modal-generic.component.scss, src/app/modules/modal-shell/modal-generic/modal-generic.component.spec.ts, src/app/modules/modal-shell/modal-generic/modal-generic.component.ts, src/app/modules/modal-shell/modal-generic/modal-generic.model.ts, src/app/modules/modal-shell/modal-shell.module.ts, src/app/modules/table2/table-header/table-header.component.html, src/app/modules/table2/table-info-modal/table-info-modal.component.html, src/app/modules/table2/table-info-modal/table-info-modal.component.spec.ts, src/app/modules/table2/table-info-modal/table-info-modal.component.ts, src/app/modules/table2/table.models.ts, src/app/modules/table2/table.module.ts, src/app/modules/table2/table.stories.ts
move the generic modal component into the design system
=> Add an option to add an informational modal to table headers

src/app/modules/table2/table-cell/table-cell.component.html, src/app/modules/table2/table.component.html, src/app/modules/table2/table.models.ts, src/app/modules/table2/table.stories.ts
remove unneeded div to place the modal icon inline on a table cell
add an optional cellclass to the table cell model
=> enhancements to the table component

src/app/modules/card-cluster/card-cluster.component.html, src/app/modules/card-cluster/card-cluster.models.ts, src/app/modules/card-cluster/card-cluster.stories.ts
feat(card-cluster): add new param to card cluster model to change styling of main card title. add story
=> Add new param to card cluster model for title styling

src/app/modules/button/button.component.css, src/app/modules/button/button.component.scss, src/app/modules/button/button.component.ts
- Darken text/border color of buttons that have outlines (and white backgrounds) to make it AAA
compliant by having a higher contrast
- Change css > scss to make use of CMS DS variables
=> fix(app-button): Improve Button Accessibility

public_api.ts
Forgot to run `npm run build` before pushing my branch, and learned all about it.
=> fix(DataTestDirective): fix build, publish by adding public_api export

src/app/modules/table/table-data/table-data.component.html, src/app/modules/table/table.module.ts
Include an optional tooltip in a table cell. Will be used for new Delayed status in file upload table, and eventually other statuses.
=> Feature/hqrpp 35724/table cell tooltip

src/app/modules/tooltip/tooltip.component.ts, src/app/modules/tooltip/tooltip.models.ts
Allow tooltips to be clickable.
=> Allow "interactive" tooltips

src/app/modules/chip-filter/chip-filter.component.html, src/app/modules/chip-filter/chip-filter.component.scss, src/app/modules/chip-filter/chip-filter.component.ts
Adds keyboard navigation functionality to the chip-filter component used for creating the reporting UI Providers select drop-downs on various forms.  
https://user-images.githubusercontent.com/115558877/195112358-fc526461-0df0-4e5b-8f2a-ffccca1be98c.mov
=> Hotfix/hqrpp 36100/app chip filter keyboard nav 508

src/app/app.component.html, src/app/modules/text-field/text-field.component.html
Also because apparently you need a space between the colon and the rest of the commit message for the NPM build Action to fire
... now that I type it out... I think I've been burned by this before and apparently refused to learn.
=> fix(text-field): multiline required and aria-required

src/app/app.component.html, src/app/app.component.ts, src/app/modules/choice/choice.component.html, src/app/modules/text-field/text-field.component.html
* error message element's aria-label includes both message and title
=> fix(text-field): role=alert changed to aria-live polite

src/app/modules/chip-filter/chip-filter.component.html, src/app/modules/chip-filter/chip-filter.component.ts
[HQRPP-36101](https://qnetjira.cms.gov/browse/HQRPP-36101) Add aria text to signal when providers load after search is complete
=> fix(chip-filter.component.html): Add aria text to signal when providers load after search is complete

src/app/modules/chip-filter/chip-filter.component.html
Add comment for ARIA message so it's apparent why the message is repeated in VoiceOver.
=> fix(chip-filter.component.html): Add comment so it's apparent why the message is repeated in VoiceOver.

src/app/modules/modal-shell/modal-generic/modal-generic.component.ts, src/app/modules/table2/table-info-modal/table-info-modal.component.html, src/app/modules/table2/table-info-modal/table-info-modal.component.ts
On modal close, put focus back on originating button.
=> Fix/hqrpp 36109/modal button focus
